name: Deploy to AKS

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Checkout Code
    - name: Checkout code
      uses: actions/checkout@v3

    # Azure Login
    - name: Log in to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    # ACR Login
    - name: Log in to ACR
      run: |
        az acr login --name myregistryleila

    # Build and Push Docker Image
    - name: Build and push Docker image to ACR
      run: |
        docker build -t myregistryleila.azurecr.io/flaskapp:${{ github.sha }} .
        docker tag myregistryleila.azurecr.io/flaskapp:${{ github.sha }} myregistryleila.azurecr.io/flaskapp:latest
        docker push myregistryleila.azurecr.io/flaskapp:${{ github.sha }}
        docker push myregistryleila.azurecr.io/flaskapp:latest

    # Get Kubernetes Credentials
    - name: Get AKS Credentials
      run: |
        az aks get-credentials --resource-group sse --name sse-aks --overwrite-existing

    # Verify Kubernetes Context
    - name: Verify Kubernetes Context
      run: |
        kubectl cluster-info

    # Update Secrets in Kubernetes
    - name: Update Secrets in Kubernetes
      run: |
        kubectl delete secret openai-secret || true
        kubectl create secret generic openai-secret --from-literal=OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}

    # Deploy to Kubernetes
    - name: Deploy to AKS
      run: |
        kubectl set image deployment/flask-app flask-app=myregistryleila.azurecr.io/flaskapp:${{ github.sha }}
        kubectl rollout status deployment/flask-app
