name: Deploy to AKS

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: 检出代码
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: 登录到 Azure CLI
    - name: Log in to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    # Step 3: 登录 Azure Container Registry (ACR)
    - name: Log in to ACR
      run: |
        az acr login --name myregistryleila

    # Step 4: 构建并推送 Docker 镜像到 ACR
    - name: Build and push Docker image
      run: |
        docker build -t myregistryleila.azurecr.io/flaskapp:${{ github.sha }} .
        docker push myregistryleila.azurecr.io/flaskapp:${{ github.sha }}

    # Step 5: 更新 Kubernetes 部署
    - name: Deploy to AKS
      run: |
        kubectl set image deployment/flask-app flask-app=myregistryleila.azurecr.io/flaskapp:${{ github.sha }}
