name: Deploy to AKS

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Log in to ACR
      run: |
        az acr login --name myregistryleila

    - name: Build and push Docker image
      run: |
        docker build -t myregistryleila.azurecr.io/flaskapp:${{ github.sha }} .
        docker push myregistryleila.azurecr.io/flaskapp:${{ github.sha }}

    - name: Run container
      run: |
        docker run -d -p 8080:80 myregistryleila.azurecr.io/flaskapp:latest
